<!-- <nav class="top-bar">
    <ul class="title-area">
        <li class="name">
            <h1><a href="{ref:idcat-0}">moraso CMS</a></h1>
        </li>
        <li class="toggle-topbar menu-icon">
            <a href="#"><span>menu</span></a>
        </li>
    </ul>

    <section class="top-bar-section">
        <?php echo Moraso_Html_Helper_Navigation_Foundation_Topbar::getHtml($this->nav, null, array('right')); ?>
    </section>
</nav> -->

<div id="mainNav">
	<div class="menu-main-container">
		<ul id="menu-main" class="sf-menu">
			<li id="blockLink2" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2"><a href="#block2">The Service</a>
			 	<!--<ul class="sub-menu">
			   		<li id="menu-item-6" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6"><a href="sample-page/full-width-page/index.html">Full Width Page</a></li>
			   		<li id="menu-item-218" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-218"><a href="#">Nothing Here</a></li>
			    </ul>-->
			</li>
			<li id="blockLink3" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-3"><a href="#block3">Portfolio</a></li>
			<li id="blockLink4" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4"><a href="#block4">About</a></li>
			<li id="blockLink5" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5"><a href="#block5">Free Advice</a></li>
			<li id="blockLink6" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6"><a href="#block6">Partners</a></li>
			<li id="blockLink7" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7"><a href="#block7">Contact</a></li>
			<li id="" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-8"><a href="#">EN</a>&nbsp;|&nbsp;<a href="#">DE</a></li>
		</ul>
	</div>
</div>