

<div class="row">    
    <div class="large-9 push-3 columns">
        <script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            tag = h2
        </script>
        
        <hr />
        <script type="application/x-moraso" src="HTML.Content:Teaser"></script>
        <script type="application/x-moraso" src="HTML.Content:Fliesstext"></script>
        <script type="application/x-moraso" src="Image:Bild1"></script>

    </div>

    
</div>