<script type="application/x-moraso" src="List.Articles:Home">
	categories = config
	useOfStartArticle = config
	template = config
	populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Service">
    categories = 2
    useOfStartArticle = 3
    orderBy = created
    template = block2
    populateWith.content.index = Fliesstext
</script>

<script type="application/x-moraso" src="List.Articles:Portfolio">
    categories = 3
    useOfStartArticle = 3
    orderBy = created
    template = block3
    populateWith.content.index = Fliesstext
</script>

<script type="application/x-moraso" src="List.Articles:About">
    categories = 4
    useOfStartArticle = 3
    orderBy = created
    template = block4
    populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Free">
    categories = 5
    useOfStartArticle = 3
    orderBy = created
    template = block5
    populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Partners">
    categories = 6
    useOfStartArticle = 3
    orderBy = created
    template = block6
    populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Contact">
    categories = 7
    useOfStartArticle = 3
    orderBy = created
    template = block7
    populateWith.content.index = Fliesstext
</script> 		