<div id="block1"  class="parallax-container"  style="background: url(images/backgrounds/DSC04350.jpg); overflow: hidden; min-height:1000px; background-repeat:repeat;">
                     <div class="story">
                        <div class=" float-left blockText" style="background:none; color:#fff; width: 900px;  ">		<br /><br /><br /><br />	<br /><br />								
                        	<span class="head1">Welcome to </span><br />
                            <span class="head1">Friday's garden </span>
																
                         </div>
                                             
                       					</div> <!--.story-->																				
			    </div>	
                
                		
			 <style>#content #block2 a {color: #;}</style>                   <div id="block2"  class="parallax-container"  style="background-image: url(images/backgrounds/carey-rear.jpg); overflow: hidden; min-height:1000px; background-color:#efefe3; background-repeat:no-repeat;">
                     <div class="story">
                        <div class="float-left blockText" style=" color:#fff; background: #a9c938;">									
                        	<h1>The Service</h1><br /><br />
                          <p><strong>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent est lectus, malesuada ac tempus id, hendrerit vel ante.</strong></p>
                            <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent est lectus, malesuada ac tempus id, hendrerit vel ante. Nam vel augue dui. Donec sit amet tempus mi. Phasellus ut semper dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                            <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent est lectus, malesuada ac tempus id, hendrerit vel ante. Nam vel augue dui. Donec sit amet tempus mi. Phasellus ut semper dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
	
                         </div>
                                             <div class="bg1" style="background-image: url(images/blob.png); min-height:1000px; height:1000px;">
                    &nbsp;</div>                     
			   </div> <!--.story-->																				
			    </div>	
			    

			    
			    
			    
<script type="application/x-moraso" src="List.Articles:Home">
	categories = config
	useOfStartArticle = config
	template = config
	populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Service">
    categories = 2
    useOfStartArticle = 3
    orderBy = created
    template = block2
    populateWith.content.index = Fliesstext
</script>

<script type="application/x-moraso" src="List.Articles:Portfolio">
    categories = 3
    useOfStartArticle = 3
    orderBy = created
    template = block3
    populateWith.content.index = Fliesstext
</script>

<script type="application/x-moraso" src="List.Articles:About">
    categories = 4
    useOfStartArticle = 3
    orderBy = created
    template = block4
    populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Free">
    categories = 5
    useOfStartArticle = 3
    orderBy = created
    template = block5
    populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Partners">
    categories = 6
    useOfStartArticle = 3
    orderBy = created
    template = block6
    populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Contact">
    categories = 7
    useOfStartArticle = 3
    orderBy = created
    template = block7
    populateWith.content.index = Fliesstext
</script> 		