<!-- <div class="row">
    <div class="large-12 columns">

            <script type="application/x-moraso" src="Image:featured">
                width = 1000
                height = 400
                template = featured
            </script>
    </div>
</div> -->


<div id="headerBar" class="clearfix" style="z-index:0">
	<div id="header" class="clearfix">
    	<div id="logo">
	    	<a href="#block1"><img src="/skin/images/friday-logo.png" border="0" /></a>
	    </div>
	    <script type="application/x-moraso" src="Navigation:main"></script>
	</div>
</div>