<!-- block2 -->
<?php foreach ($this->articles as $article) : ?>
<div id="block2" class="parallax-container" style="background-image: url(/image/1920/1440/0/<?php echo $article->idart; ?>/<?php echo $article->mainimage; ?>); overflow: hidden; min-height:1000px; background-color:#efefe3; background-repeat:no-repeat;">
	<div class="story">
    	<div class="float-left blockText" style=" color:#fff; background: #9fa316;">									
        	<h1><?php echo $article->pagetitle; ?></h1>
            <h2><?php echo $article->intro; ?></h2>
            <?php echo $article->content; ?>               
            <?php $images = unserialize($article->bild); ?>
        </div>
        <div class="bg" style="min-height:1000px; height:1000px;"><img src="/image/300/200/1/<?php echo $article->idart; ?>/<?php echo $images[0]; ?>" height="200" width="300"></div>                     
    </div>
</div>		   
<?php endforeach; ?>