<!-- block1 -->
<?php foreach ($this->articles as $article) : ?>
    <div id="block1" class="parallax-container"  style="background-image: url(/image/1920/1440/0/<?php echo $article->idart; ?>/<?php echo $article->mainimage; ?>); overflow: hidden; min-height:1000px; background-color:#efefe3; background-repeat:no-repeat;">
        <div class="story">
            <div class="float-left blockText" style="width: 600px;">									
                <span class="head1"><?php echo $article->pagetitle; ?></span><br />
                <br /><br />
                <span style="color: #fff; background: #9fa316; line-height: 1.8em; font-size: 150%; padding: 5px;">
                    <?php echo $article->teaser; ?>
                </span>		
            </div>
            <div class="bg1" style="background-image: url(files/2011/05/blob.png); min-height:1000px; height:1000px;">&nbsp;</div>                     
        </div>
    </div>		   
<?php endforeach; ?>