<!-- block4 -->
<?php foreach ($this->articles as $article) : ?>
<?php $images = unserialize($article->bild); ?>
<div id="block4" class="parallax-container"  style="background-image: url(/image/1920/1440/0/<?php echo $article->idart; ?>/<?php echo $article->mainimage; ?>); overflow: hidden; min-height:1000px; background-color:#efefe3; background-repeat:no-repeat;">
	<div class="story">
    	<div class="float-left blockText" style=" color:#fff; background: #9fa316; width: 500px;">									
        	<h1><?php echo $article->pagetitle; ?></h1>
            <h2><?php echo $article->intro; ?></h2>
            <?php echo $article->content; ?>
        </div>
        <div class="float-right blockText" style="min-height:1000px; height:1000px;">
        	<?php foreach ($images as $image) : ?>
            <div style="border: 5px solid white;">
            <img src="/image/340/299/1/<?php echo $article->idart; ?>/<?php echo $image; ?>" title="<?php echo $article->pagetitle; ?>">
            </div>                     
            <?php endforeach; ?>
        </div>
    </div>
</div>    		   
<?php endforeach; ?>