<!-- block5 -->
<?php foreach ($this->articles as $article) : ?>
    <div id="block5" class="parallax-container"  style="background-image: url(/image/1920/1440/0/<?php echo $article->idart; ?>/<?php echo $article->mainimage; ?>); overflow: hidden; min-height:1000px; background-color:#efefe3; background-repeat:no-repeat;">
        <div class="story">
            <div class="float-left blockText" style=" color:#fff; background: #9fa316; width: 500px;">									
                <h1><?php echo $article->pagetitle; ?></h1><br /><br />
                <?php echo $article->content; ?>

                <?php $imagesfive = unserialize($article->bild); ?>

            </div>
                    <div><img src="/image/300/200/1/<?php echo $article->idart; ?>/<?php echo $imagestwo[0]; ?>" height="200" width="300"></div>                     
                     
        </div>
    </div>		   
<?php endforeach; ?>