<!-- block2 -->
<?php foreach ($this->articles as $article) : ?>
    <div id="block2" class="post-78 post type-post status-publish format-standard hentry category-beautiful parallax-container" style="background-image: url(/image/1920/1440/0/<?php echo $article->idart; ?>/<?php echo $article->mainimage; ?>); overflow: hidden; min-height:1000px; background-color:#efefe3; background-repeat:no-repeat;">
        <div class="story">
            <div class="float-left blockText" style=" color:#fff; background: #a9c938;">									
                <h1><?php echo $article->pagetitle; ?></h1><br /><br />
                <p><?php echo $article->content; ?></p>
            </div>
            <div class="bg1" style="background-image: url(files/2011/05/blob.png); min-height:1000px; height:1000px;">&nbsp;</div>                     
        </div>
    </div>		   
<?php endforeach; ?>